package id.ac.ui.cs.advprog.order.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    ORDER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    SELF_PURCHASE_NOT_ALLOWED,
    INSUFFICIENT_STOCK,
    VOUCHER_INVALID,
    WALLET_INSUFFICIENT,
    CHECKOUT_FAILED,
    ORDER_ALREADY_CANCELLED,
    ORDER_ALREADY_COMPLETED,
    INVALID_STATUS_TRANSITION,
    CANCEL_NOT_ALLOWED,
    RATING_ALREADY_EXISTS,
    RATING_ONLY_WHEN_COMPLETED,
    INTERNAL_ERROR
}