package id.ac.ui.cs.advprog.order.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    ORDER_NOT_FOUND,
    INVALID_ORDER_STATUS_TRANSITION,
    ORDER_CANCELLATION_NOT_ALLOWED,
    ORDER_ALREADY_RATED,
    ORDER_NOT_COMPLETED,
    PRODUCT_NOT_FOUND,
    BUYER_OWNS_PRODUCT,
    INSUFFICIENT_STOCK,
    VOUCHER_INVALID,
    WALLET_INSUFFICIENT,
    CHECKOUT_FAILED,
    CHECKOUT_IN_PROGRESS,
    IDEMPOTENCY_CONFLICT,
    INTERNAL_ERROR
}
