spring.application.name=Order

server.port=${PORT:8080}
spring.profiles.default=prod
voucher.service.base-url=${VOUCHER_SERVICE_BASE_URL:http://18.232.174.224}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health,info
logging.level.id.ac.ui.cs.advprog.order=INFO

