DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS idempotency_records;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    jastiper_id BIGINT,
    status VARCHAR(32) NOT NULL,
    shipping_address VARCHAR(500) NOT NULL,
    subtotal DECIMAL(19,2) NOT NULL,
    discount_total DECIMAL(19,2) NOT NULL,
    total_paid DECIMAL(19,2) NOT NULL,
    voucher_code VARCHAR(50),
    failure_reason VARCHAR(500),
    refund_done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(200) NOT NULL,
    unit_price_snapshot DECIMAL(19,2) NOT NULL,
    qty INT NOT NULL,
    line_total DECIMAL(19,2) NOT NULL
);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idem_key VARCHAR(80) NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL,
    endpoint VARCHAR(50) NOT NULL,
    request_hash VARCHAR(120) NOT NULL,
    order_id BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL,
    product_rating INT NOT NULL,
    jastiper_rating INT NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_orders_buyer_id ON orders(buyer_id);
CREATE INDEX idx_orders_jastiper_id ON orders(jastiper_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE TABLE order_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    actor_id BIGINT,
    event VARCHAR(30) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_order_id ON order_audit_logs(order_id);
CREATE INDEX idx_audit_actor_id ON order_audit_logs(actor_id);