DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS idempotency_records;
DROP TABLE IF EXISTS ratings;

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id BIGINT NOT NULL,
                        jastiper_id BIGINT,
                        status VARCHAR(32) NOT NULL,
                        shipping_address VARCHAR(500) NOT NULL,
                        subtotal DECIMAL(19,2) NOT NULL,
                        discount_total DECIMAL(19,2) NOT NULL,
                        total_paid DECIMAL(19,2) NOT NULL,
                        voucher_code VARCHAR(50),
                        refund_done BOOLEAN DEFAULT FALSE,
                        created_at TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             product_name_snapshot VARCHAR(200) NOT NULL,
                             unit_price_snapshot DECIMAL(19,2) NOT NULL,
                             qty INT NOT NULL,
                             line_total DECIMAL(19,2) NOT NULL
);

CREATE INDEX idx_orders_buyer_id ON orders(buyer_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);